# Config file for automatic testing at travis-ci.org
dist: bionic
language: python

python:
    - "2.7"
    - "3.5"
    - "3.6"
    - "3.7"

before_install:
    - sudo add-apt-repository ppa:maarten-fonville/protobuf -y
    - sudo apt-get update -qq
    # We have to install protoc, and python libs for both python and python3, since mypy runs py3
    - sudo apt-get install -qq protobuf-compiler python-protobuf python3-protobuf python3 python3-pip python3-setuptools
    - python -m pip install virtualenv
    - python3 -m pip install virtualenv
script:
    - ./run_test.sh
